/*
 * Copyright (C) 2005, The Beangle Software.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.beangle.data.hibernate.proxy

import org.hibernate.HibernateException
import org.hibernate.bytecode.enhance.spi.{EnhancementContext, Enhancer}
import org.hibernate.bytecode.spi.{BytecodeProvider, ProxyFactoryFactory, ReflectionOptimizer}
import org.hibernate.property.access.spi.PropertyAccess

/** 按名加载构建期预生成代理类的 Hibernate BytecodeProvider。
 *
 * 代理类在构建期由 [[BeangleProxyGenerator]] 生成并打进 jar，
 * 类名固定为 `<Entity>$HibernateProxy`；运行期（JVM 与 native 同路径）不再需要 ByteBuddy：
 * 本 provider 不引用任何 net.bytebuddy 类，`getProxy` 仅做无参实例化并挂上
 * [[BeangleInterceptor]]（本包提供的拦截器，由上游 `ByteBuddyInterceptor` 改名而来）。
 *
 * 通过 `META-INF/services/org.hibernate.bytecode.spi.BytecodeProvider` 注册，
 * 取代 hibernate-core 默认的 bytebuddy provider（fork 已从 shaded jar 剔除该 SPI）。
 */
class PrebuiltProxyProvider extends BytecodeProvider {

  override def getProxyFactoryFactory(): ProxyFactoryFactory = new BeangleProxyFactoryFactory

  override def getReflectionOptimizer(clazz: Class[_], getterNames: Array[String], setterNames: Array[String],
      types: Array[Class[_]]): ReflectionOptimizer = {
    throw new HibernateException(
      "Using the ReflectionOptimizer is not possible with the configured pre-generated BytecodeProvider")
  }

  override def getReflectionOptimizer(clazz: Class[_], propertyAccessMap: java.util.Map[String, PropertyAccess]): ReflectionOptimizer = null

  override def getEnhancer(enhancementContext: EnhancementContext): Enhancer = null
}
